name: EscapeUtils
main: net.escapecraft.escapeutils.EscapeUtils
version: ${project.version}
commands:
    last:
        description: Returns position or target player's position
        usage: /<command> [player]
permissions:
  escapeutils.*:
    description: Supernode for EscapeUtils commands.
    children:
      escapeplug.last: true
  escapeutils.last:
    description: Use all LastReport features
    children:
      escapeutils.last.death: true
      escapeutils.last.login: true
  escapeutils.last.death:
    description: Use last command on self
    default: op
  escapeutils.last.login:
    description: Use last command on other
    default: op